sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    
    - GOOGLE_APPLICATION_CREDENTIALS=service-accounts.json
    - GOOGLE_CLOUD_PROJECT=multi-k8s-2861
    - GOOGLE_CLOUD_ZONE=us-central1-a 
    - GOOGLE_CLOUD_CLUSTER=multi-cluster
    - DOCKER_USERNAME=exodiums
    - KUBECONFIG=$HOME/.kube/config
    - KUBE_NAMESPACE=default
    - KUBE_CLUSTER_NAME=multi-cluster
    - KUBE_SERVER=https://
before_install:
    - openssl aes-256-cbc -K $encrypted_6f1620002b70_key -iv $encrypted_6f1620002b70_iv -in service-accounts.json.enc -out service-accounts.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-accounts.json
    - gcloud config set project multi-k8s-2861
    - gcloud config set compute/zone us-central1-a
    - gcloud container clusters get-credentials multi-cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true exodiums/react-test npm test

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
      branch: main