apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 # Aynı cluster içindeki diğer podların erişim sağlayacağı port 
      targetPort: 3000 # poda erişim sağlanacak olan port