apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage # volume name and mount name are identical, it means go back out to the volumes entry and find some thing called postgres-storage
              mountPath: /var/lib/postgresql/data # this is the path inside the container that volumes will be mounted
              subPath: postgres # this option means that any data inside the container that is stored inside of mountPath is going to be stored inside of a folder, called Postgres.
              # persistent volume içinde postgres adında bir klasörde depolanacak.
          env:
            - name: POSTGRES_PASSWORD # 12345asdf
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD